version: "3.9"

services:
  #Brocker
  Broker:
    image: cpabe-dev-image:0.0
    build: ./dockerfiles/Base/
    tty: true
    volumes:
      - ./codes/Broker/:/code
    working_dir: /code
    ports:
      - "1883:1883"
      - "443:443"
    # command: "" 
    # environment:
    networks:
      devnetwork:
        ipv4_address: 10.1.0.1

  #Proxy
  Proxy:
    image: cpabe-dev-image:0.0
    build: ./dockerfiles/Base/
    tty: true
    volumes:
      - ./codes/Proxy/:/code
    working_dir: /code
    ports:
      - "8080:8080"
    # command: "" 
    # environment:
    networks:
      devnetwork:
        ipv4_address: 10.1.0.2

networks:
  devnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/24
         gateway: 10.1.0.254